version: '2.2'
services:
  nginx:
    build: docker/contaners/nginx
    volumes_from:
      - fpm:rw
    links:
      - fpm
    ports:
      - 443:443
    environment:
      TZ: "Europe/Zurich"
    restart: always
    volumes:
        - ./:/var/www/html

  fpm:
    build: docker/contaners/fpm
    volumes:
      - ./:/var/www:rw
    links:
      - mariadb
      - mongo
      - redis
    environment:
      XDEBUG_CONFIG: remote_host=${REMOTE_HOST}
      TZ: "Europe/Zurich"
    restart: always

  mariadb:
    build: docker/contaners/mariadb
    ports:
      - 3306:3306
    volumes:
      - ./docker/database/mariadb:/var/lib/mysql:rw
    environment:
      MYSQL_ROOT_PASSWORD: 123
      MYSQL_DATABASE: laravel
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql
      TZ: "Europe/Zurich"
    restart: always

  mongo:
    image: mongo:3.6
    #    environment:
    #      MONGO_INITDB_ROOT_USERNAME: root
    #      MONGO_INITDB_ROOT_PASSWORD: 123
    volumes:
      - ./docker/database/mongo:/var/lib/mongodb
    restart: always

  redis:
    image: redis
    volumes:
      - ./docker/database/redis:/data
    restart: always
